# Generated by Django 5.0.7 on 2024-08-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdetails',
        ),
    ]
