# Generated by Django 5.0.7 on 2024-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.TextField(default=25, max_length=1000),
            preserve_default=False,
        ),
    ]
