# Generated by Django 5.0.7 on 2024-08-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userdetails_email_userdetails_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='username',
        ),
    ]
