# Generated by Django 5.0.7 on 2024-08-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_userdetails_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='name',
            field=models.TextField(default=127, max_length=1000),
            preserve_default=False,
        ),
    ]
