# Generated by Django 5.0.7 on 2024-08-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userdetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
