# Generated by Django 5.0.7 on 2024-08-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userdetails_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name=''),
            preserve_default=False,
        ),
    ]
